try to fix babel config
/app/.build/client/src/components/modal/confirm.js:17
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(confirmButtonText, type) {
                                             ^

ReferenceError: regeneratorRuntime is not defined
    at /app/.build/client/src/components/modal/confirm.js:17:46
    at Object.<anonymous> (/app/.build/client/src/components/modal/confirm.js:47:2)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/.build/client/src/components/card/index.js:24:39)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

Signed-off-by: Kingdon Barrett <kingdon@weave.works>